FROM ubuntu:latest

# update and upgrade the system
RUN apt-get update && apt-get upgrade -y

# install the required packages
RUN apt-get install -y nginx vim

#define the command to run when the container starts
CMD ["nginx", "-g", "daemon off;"]